# Generated by Django 2.2.4 on 2019-10-03 10:47

from django.db import migrations, models


def populate_createdby_name(apps, schema_editor):
    for obj_type in (
        "OptOut",
        "BabySwitch",
        "ChannelSwitch",
        "PublicRegistration",
        "PrebirthRegistration",
        "PostbirthRegistration",
    ):
        Model = apps.get_model("eventstore", obj_type)
        for m in Model.objects.select_related("created_by").all().iterator():
            m.created_by_name = m.created_by.username
            m.save(update_fields=("created_by_name",))


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0006_create_postbirthregistration")]

    operations = [
        migrations.AddField(
            model_name="babyswitch",
            name="created_by_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="channelswitch",
            name="created_by_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="optout",
            name="created_by_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="postbirthregistration",
            name="created_by_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="prebirthregistration",
            name="created_by_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="publicregistration",
            name="created_by_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(populate_createdby_name),
        migrations.RemoveField(model_name="babyswitch", name="created_by"),
        migrations.RemoveField(model_name="channelswitch", name="created_by"),
        migrations.RemoveField(model_name="optout", name="created_by"),
        migrations.RemoveField(model_name="postbirthregistration", name="created_by"),
        migrations.RemoveField(model_name="prebirthregistration", name="created_by"),
        migrations.RemoveField(model_name="publicregistration", name="created_by"),
        migrations.RenameField(
            model_name="babyswitch", old_name="created_by_name", new_name="created_by"
        ),
        migrations.RenameField(
            model_name="channelswitch",
            old_name="created_by_name",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="optout", old_name="created_by_name", new_name="created_by"
        ),
        migrations.RenameField(
            model_name="postbirthregistration",
            old_name="created_by_name",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="prebirthregistration",
            old_name="created_by_name",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="publicregistration",
            old_name="created_by_name",
            new_name="created_by",
        ),
    ]
