# Generated by Django 2.2.8 on 2020-01-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventstore", "0015_add_research_optin_switch")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="fallback_channel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="fallback_channel",
            field=models.BooleanField(default=False),
        ),
    ]
