# Generated by Django 2.2.4 on 2020-01-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0017_pmtctregistration")]

    operations = [
        migrations.AlterField(
            model_name="pmtctregistration",
            name="pmtct_risk",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("High", "High")], max_length=6
            ),
        )
    ]
