# Generated by Django 2.2.4 on 2020-02-19 10:22

import uuid

import django.contrib.postgres.fields.jsonb
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0018_auto_20200205_1033")]

    operations = [
        migrations.CreateModel(
            name="DeliveryFailures",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_id", models.CharField(blank=True, max_length=255)),
                ("number_of_failures", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
            ],
        )
    ]
