# Generated by Django 2.2.4 on 2020-02-24 09:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eventstore', '0019_babydobswitch_eddswitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFailures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_id', models.CharField(blank=True, max_length=255)),
                ('number_of_failures', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
