# Generated by Django 2.2.8 on 2020-04-02 14:45

import uuid

import django.contrib.postgres.fields.jsonb
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0020_auto_20200302_1458")]

    operations = [
        migrations.CreateModel(
            name="Covid19Triage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("msisdn", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ZA-GT", "Gauteng"),
                            ("ZA-NW", "North-West (South Africa)"),
                            ("ZA-LP", "Limpopo"),
                            ("ZA-WC", "Western Cape"),
                            ("ZA-MP", "Mpumalanga"),
                            ("ZA-EC", "Eastern Cape"),
                            ("ZA-NC", "Northern Cape"),
                            ("ZA-FS", "Free State"),
                            ("ZA-NL", "Kwazulu-Natal"),
                        ],
                        max_length=6,
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("<18", "<18"),
                            ("18-40", "18-40"),
                            ("40-65", "40-65"),
                            (">65", ">65"),
                        ],
                        max_length=5,
                    ),
                ),
                ("fever", models.BooleanField()),
                ("cough", models.BooleanField()),
                ("sore_throat", models.BooleanField()),
                (
                    "exposure",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not_sure", "Not sure"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "tracing",
                    models.BooleanField(
                        help_text="Whether the NDoH can contact the user"
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=8,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
            ],
        )
    ]
