# Generated by Django 2.2.8 on 2020-04-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventstore", "0022_cdu_address_update")]

    operations = [
        migrations.AddField(
            model_name="cduaddressupdate",
            name="msisdn",
            field=models.CharField(default="Empty", max_length=255),
            preserve_default=False,
        )
    ]
