# Generated by Django 2.2.8 on 2020-04-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0023_cdu_address_update_msisdn")]

    operations = [
        migrations.AddField(
            model_name="cduaddressupdate",
            name="district",
            field=models.CharField(default="Empty", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cduaddressupdate",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
