# Generated by Django 2.2.8 on 2020-04-08 12:44

import django.utils.timezone
from django.db import migrations, models


def set_default(apps, schema_editor):
    Covid19Triage = apps.get_model("eventstore", "Covid19Triage")
    Covid19Triage.objects.update(completed_timestamp=models.F("timestamp"))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("eventstore", "0027_normalise_msisdn")]

    operations = [
        migrations.AddField(
            model_name="covid19triage",
            name="completed_timestamp",
            field=models.DateTimeField(null=True, default=None),
        ),
        migrations.RunPython(set_default, noop),
        migrations.AlterField(
            model_name="covid19triage",
            name="completed_timestamp",
            field=models.DateTimeField(null=False, default=django.utils.timezone.now),
        ),
    ]
