# Generated by Django 2.2.8 on 2020-05-07 10:02

from django.db import migrations, models

import registrations.validators


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0029_add_index_on_timestamp")]

    operations = [
        migrations.AddField(
            model_name="covid19triage",
            name="city_location",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                validators=[registrations.validators.geographic_coordinate],
            ),
        ),
        migrations.AddField(
            model_name="covid19triage",
            name="confirmed_contact",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="covid19triage",
            name="date_of_birth",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="covid19triage",
            name="first_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="covid19triage",
            name="last_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="covid19triage",
            name="persons_in_household",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="covid19triage",
            name="rooms_in_household",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
