# Generated by Django 2.2.8 on 2020-08-05 09:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("eventstore", "0030_add_covid19_confirmed_contact_fields")]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX CONCURRENTLY "covid19triage_msisdn"
            on "eventstore_covid19triage" ("msisdn");
            """,
            reverse_sql="""
            DROP INDEX CONCURRENTLY IF EXISTS "convid19triage_msisdn";
            """,
        )
    ]
