# Generated by Django 2.2.13 on 2020-07-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0031_add_healthcheck_index_msisdn")]

    operations = [
        migrations.AddField(
            model_name="deliveryfailure",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        )
    ]
