# Generated by Django 2.2.8 on 2020-08-05 09:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("eventstore", "0032_add_healthcheck_user_profile")]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP INDEX CONCURRENTLY IF EXISTS
            "eventstore_healthcheckuserprofile_msisdn_589e16ad_like";
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="""
            DROP INDEX CONCURRENTLY IF EXISTS
            "eventstore_covid19triage_deduplication_id_72566044_like";
            """,
            reverse_sql="",
        ),
    ]
