# Generated by Django 2.2.13 on 2020-08-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0034_remove_like_indexes")]

    operations = [
        migrations.AddField(
            model_name="covid19triage",
            name="place_of_work",
            field=models.CharField(
                blank=True,
                choices=[
                    ("healthcare", "Healthcare"),
                    ("education", "Education"),
                    ("port_of_entry", "Port of entry"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=13,
                null=True,
            ),
        )
    ]
