# Generated by Django 2.2.13 on 2020-10-07 10:40

import functools

from django.db import migrations, models

import eventstore.validators


class Migration(migrations.Migration):
    dependencies = [("eventstore", "0035_covid19triage_place_of_work")]

    operations = [
        migrations.CreateModel(
            name="DBEOnBehalfOfProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msisdn",
                    models.CharField(
                        max_length=255,
                        validators=[
                            functools.partial(
                                eventstore.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("not_say", "Rather not say"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ZA-EC", "Eastern Cape"),
                            ("ZA-FS", "Free State"),
                            ("ZA-GT", "Gauteng"),
                            ("ZA-LP", "Limpopo"),
                            ("ZA-MP", "Mpumalanga"),
                            ("ZA-NC", "Northern Cape"),
                            ("ZA-NL", "Kwazulu-Natal"),
                            ("ZA-NW", "North-West (South Africa)"),
                            ("ZA-WC", "Western Cape"),
                        ],
                        max_length=6,
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                (
                    "city_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        validators=[eventstore.validators.geographic_coordinate],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        validators=[eventstore.validators.geographic_coordinate],
                    ),
                ),
                ("school", models.CharField(max_length=255)),
                ("school_emis", models.CharField(max_length=255)),
                (
                    "preexisting_condition",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not_sure", "Not sure"),
                        ],
                        max_length=9,
                    ),
                ),
                ("obesity", models.BooleanField(default=None, null=True)),
                ("diabetes", models.BooleanField(default=None, null=True)),
                ("hypertension", models.BooleanField(default=None, null=True)),
                ("cardio", models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="dbeonbehalfofprofile",
            index=models.Index(fields=["msisdn"], name="eventstore__msisdn_3a3304_idx"),
        ),
    ]
