# Generated by Django 2.2.13 on 2020-11-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventstore", "0036_auto_20201007_1040")]

    operations = [
        migrations.AddField(
            model_name="dbeonbehalfofprofile",
            name="asthma",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="dbeonbehalfofprofile",
            name="cardiac",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="dbeonbehalfofprofile",
            name="immuno",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="dbeonbehalfofprofile",
            name="pregnant",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="dbeonbehalfofprofile",
            name="respiratory",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="dbeonbehalfofprofile",
            name="tb",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
