# Generated by Django 2.2.13 on 2021-01-14 10:39

import functools

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import registrations.validators


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0037_add_expanded_comorbidities")]

    operations = [
        migrations.CreateModel(
            name="MomConnectImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Validating"),
                            (1, "Validated"),
                            (2, "Uploading"),
                            (3, "Complete"),
                            (4, "Error"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField()),
                (
                    "msisdn",
                    models.CharField(
                        max_length=255,
                        validators=[
                            functools.partial(
                                registrations.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                ("messaging_consent", models.BooleanField()),
                ("research_consent", models.BooleanField(default=False)),
                ("previous_optout", models.BooleanField(default=False)),
                ("facility_code", models.CharField(max_length=6)),
                ("edd_year", models.IntegerField()),
                ("edd_month", models.IntegerField()),
                ("edd_day", models.IntegerField()),
                (
                    "id_type",
                    models.IntegerField(
                        choices=[(0, "SA ID"), (1, "Passport"), (2, "None")]
                    ),
                ),
                ("id_number", models.CharField(max_length=13)),
                ("passport_country", models.IntegerField()),
                ("passport_number", models.CharField(max_length=255)),
                ("dob_year", models.IntegerField(null=True)),
                ("dob_month", models.IntegerField(null=True)),
                ("dob_day", models.IntegerField(null=True)),
                (
                    "language",
                    models.IntegerField(
                        choices=[
                            (0, "isiZulu"),
                            (1, "isiXhosa"),
                            (2, "Afrikaans"),
                            (3, "English"),
                            (4, "Sesotho sa Leboa"),
                            (5, "Setswana"),
                            (6, "Sesotho"),
                            (7, "Xitsonga"),
                            (8, "SiSwati"),
                            (9, "Tshivenda"),
                            (10, "isiNdebele"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "mcimport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="eventstore.MomConnectImport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField()),
                (
                    "error_type",
                    models.IntegerField(
                        choices=[
                            (0, "File is not a CSV"),
                            (1, "Field {} not found in header"),
                            (2, "Field {} failed validation: {}"),
                        ]
                    ),
                ),
                ("error_args", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "mcimport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="eventstore.MomConnectImport",
                    ),
                ),
            ],
        ),
    ]
