# Generated by Django 2.2.13 on 2021-01-14 14:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0038_importerror_importrow_momconnectimport")]

    operations = [
        migrations.AlterField(
            model_name="importerror",
            name="error_args",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="dob_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="dob_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="dob_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="id_number",
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="passport_country",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="passport_number",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
