# Generated by Django 2.2.13 on 2021-01-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventstore", "0039_auto_20210118_0950")]

    operations = [
        migrations.AddField(
            model_name="momconnectimport",
            name="last_uploaded_row",
            field=models.PositiveSmallIntegerField(default=0),
        )
    ]
