# Generated by Django 2.2.13 on 2021-01-15 15:27

import django.core.validators
from django.db import migrations, models

import eventstore.validators


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0039_auto_20210114_1424")]

    operations = [
        migrations.AlterField(
            model_name="importerror",
            name="error_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "File is not a CSV"),
                    (1, "Fields {} not found in header"),
                    (2, "Field {} failed validation: {}"),
                    (3, "Failed validation: {}"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="importerror",
            name="row_number",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="dob_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="dob_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="dob_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="edd_day",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="edd_month",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="edd_year",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="facility_code",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator("\\d{6}", "Must be 6 digits")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="id_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[eventstore.validators.validate_sa_id_number],
            ),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="id_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "SA ID"), (1, "Passport"), (2, "None")]
            ),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="language",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "isiZulu"),
                    (1, "isiXhosa"),
                    (2, "Afrikaans"),
                    (3, "English"),
                    (4, "Sesotho sa Leboa"),
                    (5, "Setswana"),
                    (6, "Sesotho"),
                    (7, "Xitsonga"),
                    (8, "SiSwati"),
                    (9, "Tshivenda"),
                    (10, "isiNdebele"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="messaging_consent",
            field=models.BooleanField(validators=[eventstore.validators.validate_true]),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="passport_country",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Zimbabwe"),
                    (1, "Mozambique"),
                    (2, "Malawi"),
                    (3, "Nigeria"),
                    (4, "DRC"),
                    (5, "Somalia"),
                    (6, "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="row_number",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="momconnectimport",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Validating"),
                    (1, "Validated"),
                    (2, "Uploading"),
                    (3, "Complete"),
                    (4, "Error"),
                ],
                default=0,
            ),
        ),
    ]
