# Generated by Django 2.2.13 on 2021-03-04 14:47

import functools
import uuid

import django.utils.timezone
from django.db import migrations, models

import eventstore.validators


class Migration(migrations.Migration):
    dependencies = [("eventstore", "0040_momconnectimport_last_uploaded_row")]

    operations = [
        migrations.CreateModel(
            name="Covid19TriageStart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "msisdn",
                    models.CharField(
                        max_length=255,
                        validators=[
                            functools.partial(
                                eventstore.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
        )
    ]
