# Generated by Django 2.2.13 on 2021-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventstore", "0042_auto_20210511_1013")]

    operations = [
        migrations.RenameField(
            model_name="healthcheckuserprofile",
            old_name="hcs_study_c_arm",
            new_name="hcs_study_c_quarantine_arm",
        ),
        migrations.AddField(
            model_name="healthcheckuserprofile",
            name="hcs_study_c_testing_arm",
            field=models.CharField(
                choices=[
                    ("C", "Control"),
                    ("T1", "Treatment 1"),
                    ("T2", "Treatment 2"),
                    ("T3", "Treatment 3"),
                    ("T4", "Treatment 4"),
                ],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
    ]
