# Generated by Django 2.2.20 on 2021-07-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0044_auto_20210518_1003")]

    operations = [
        migrations.AddField(
            model_name="momconnectimport",
            name="source",
            field=models.CharField(default="MomConnect Import", max_length=255),
        )
    ]
