# Generated by Django 2.2.20 on 2021-07-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0045_momconnectimport_source")]

    operations = [
        migrations.AddField(
            model_name="importrow",
            name="baby_dob_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importrow",
            name="baby_dob_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importrow",
            name="baby_dob_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="edd_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="edd_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="edd_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
