# Generated by Django 2.2.24 on 2021-11-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventstore", "0047_remove_healthcheckuserprofile_hcs_study_c_pilot_arm")
    ]

    operations = [
        migrations.AlterField(
            model_name="importerror",
            name="error_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "File is not a CSV"),
                    (1, "Fields {} not found in header"),
                    (2, "Field {} failed validation: {}"),
                    (3, "Failed validation: {}"),
                    (4, "Mother is opted out and has not chosen to opt in again"),
                    (5, "Mother is already receiving messages"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="optout",
            name="reason",
            field=models.CharField(
                choices=[
                    ("not_useful", "Not useful"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                    ("sms_failure", "SMS failure"),
                    ("whatsapp_failure", "WhatsApp failure"),
                    ("miscarriage", "Miscarriage"),
                    ("stillbirth", "Stillbirth"),
                    ("babyloss", "Lost baby"),
                    ("not_hiv_pos", "Not HIV positive"),
                ],
                max_length=11,
            ),
        ),
    ]
