# Generated by Django 2.2.24 on 2021-12-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventstore", "0048_auto_20211110_0925")]

    operations = [
        migrations.AlterField(
            model_name="optout",
            name="reason",
            field=models.CharField(
                choices=[
                    ("not_useful", "Not useful"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                    ("sms_failure", "SMS failure"),
                    ("whatsapp_failure", "WhatsApp failure"),
                    ("miscarriage", "Miscarriage"),
                    ("stillbirth", "Stillbirth"),
                    ("babyloss", "Lost baby"),
                    ("not_hiv_pos", "Not HIV positive"),
                ],
                max_length=16,
            ),
        )
    ]
