# Generated by Django 2.2.27 on 2022-03-08 09:00

from django.db import migrations, models
import django.utils.timezone
import eventstore.validators
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('eventstore', '0052_auto_20220131_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCSStudyBRandomization',
            fields=[
                ('msisdn', models.CharField(max_length=255, primary_key=True, serialize=False, validators=[functools.partial(eventstore.validators._phone_number, *(), **{'country': 'ZA'})])),
                ('source', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('USSD', 'USSD')], max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('province', models.CharField(choices=[('ZA-EC', 'Eastern Cape'), ('ZA-FS', 'Free State'), ('ZA-GT', 'Gauteng'), ('ZA-LP', 'Limpopo'), ('ZA-MP', 'Mpumalanga'), ('ZA-NC', 'Northern Cape'), ('ZA-NL', 'Kwazulu-Natal'), ('ZA-NW', 'North-West (South Africa)'), ('ZA-WC', 'Western Cape')], max_length=6)),
                ('study_b_arm', models.CharField(choices=[('C', 'Control'), ('T1', 'Treatment 1'), ('T2', 'Treatment 2'), ('T3', 'Treatment 3')], default=None, max_length=3, null=True)),
            ],
        ),
    ]
