# Generated by Django 4.1 on 2023-03-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventstore", "0053_hcsstudybrandomization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="babydobswitch",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="babyswitch",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="channelswitch",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="chwregistration",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="chwregistration",
            name="language",
            field=models.CharField(choices=[], max_length=3),
        ),
        migrations.AlterField(
            model_name="covid19triage",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="eddswitch",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="healthcheckuserprofile",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="identificationswitch",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="importerror",
            name="error_args",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="languageswitch",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="msisdnswitch",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="optout",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="pmtctregistration",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="postbirthregistration",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="postbirthregistration",
            name="language",
            field=models.CharField(choices=[], max_length=3),
        ),
        migrations.AlterField(
            model_name="prebirthregistration",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="prebirthregistration",
            name="language",
            field=models.CharField(choices=[], max_length=3),
        ),
        migrations.AlterField(
            model_name="publicregistration",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="researchoptinswitch",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
