# Generated by Django 4.1 on 2023-03-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventstore", "0054_alter_babydobswitch_data_alter_babyswitch_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicregistration",
            name="language",
            field=models.CharField(
                choices=[
                    ("afr", "Afrikaans"),
                    ("eng", "English"),
                    ("nbl", "isiNdebele"),
                    ("nso", "Sepedi"),
                    ("sot", "Sesotho"),
                    ("ssw", "Siswati"),
                    ("tsn", "Setswana"),
                    ("tso", "Xitsonga"),
                    ("ven", "Tshivenda"),
                    ("xho", "isiXhosa"),
                    ("zul", "isiZulu"),
                    ("en", "English"),
                ],
                max_length=3,
            ),
        ),
    ]
