# Generated by Django 4.1.7 on 2023-04-06 08:23

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("eventstore", "0056_alter_event_recipient_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="message",
                    name="contact_id",
                    field=models.CharField(blank=True, db_index=True, max_length=255),
                ),
            ],
            database_operations=[
                AddIndexConcurrently(
                    model_name="message",
                    index=models.Index(fields=["contact_id"], name="contact_id_idx"),
                ),
            ],
        ),
    ]
