# Generated by Django 4.1.7 on 2023-11-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventstore", "0060_alter_optout_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optout",
            name="reason",
            field=models.CharField(
                choices=[
                    ("not_useful", "Not useful"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                    ("sms_failure", "SMS failure"),
                    ("whatsapp_failure", "WhatsApp failure"),
                    ("miscarriage", "Miscarriage"),
                    ("stillbirth", "Stillbirth"),
                    ("babyloss", "Lost baby"),
                    ("not_hiv_pos", "Not HIV positive"),
                    ("no_consent_to_privacy_policy", "no consent to privacy policy"),
                ],
                max_length=30,
            ),
        ),
    ]
