# Generated by Django 4.1.7 on 2023-11-23 09:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventstore", "0061_alter_optout_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenHIMQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("PrebirthRegistration", "PrebirthRegistration"),
                            ("CHWRegistration", "CHWRegistration"),
                            ("PublicRegistration", "PublicRegistration"),
                            ("ChannelSwitch", "ChannelSwitch"),
                            ("OptOut", "OptOut"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Processing"),
                            (2, "Complete"),
                            (3, "Error"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
    ]
