# Generated by Django 4.1.7 on 2023-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventstore", "0062_openhimqueue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openhimqueue",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("prebirth_registration", "PrebirthRegistration"),
                    ("chw_registration", "CHWRegistration"),
                    ("public_registration", "PublicRegistration"),
                    ("channel_switch", "ChannelSwitch"),
                    ("optout", "OptOut"),
                ],
                max_length=30,
            ),
        ),
    ]
