# Generated by Django 4.1.7 on 2023-11-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventstore", "0063_alter_openhimqueue_object_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="openhimqueue",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
