# Generated by Django 4.2.13 on 2024-07-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventstore", "0065_whatsapptemplatesendstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplatesendstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("wired", "Message wired"),
                    ("event_received", "Event received"),
                    ("registration_completed", "Registration completed"),
                ],
                default="wired",
                max_length=30,
            ),
        ),
    ]
