# Generated by Django 4.2.13 on 2024-07-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventstore",
            "0067_rename_registration_completed_at_whatsapptemplatesendstatus_action_completed_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplatesendstatus",
            name="contact_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsapptemplatesendstatus",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="whatsapptemplatesendstatus",
            name="flow_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
