# Generated by Django 5.1.7 on 2025-03-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventstore', '0068_whatsapptemplatesendstatus_contact_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19triage',
            name='province',
            field=models.CharField(choices=[('ZA-EC', 'Eastern Cape'), ('ZA-FS', 'Free State'), ('ZA-GP', 'Gauteng'), ('ZA-KZN', 'Kwazulu-Natal'), ('ZA-LP', 'Limpopo'), ('ZA-MP', 'Mpumalanga'), ('ZA-NC', 'Northern Cape'), ('ZA-NW', 'North-West'), ('ZA-WC', 'Western Cape')], max_length=6),
        ),
        migrations.AlterField(
            model_name='dbeonbehalfofprofile',
            name='province',
            field=models.CharField(choices=[('ZA-EC', 'Eastern Cape'), ('ZA-FS', 'Free State'), ('ZA-GP', 'Gauteng'), ('ZA-KZN', 'Kwazulu-Natal'), ('ZA-LP', 'Limpopo'), ('ZA-MP', 'Mpumalanga'), ('ZA-NC', 'Northern Cape'), ('ZA-NW', 'North-West'), ('ZA-WC', 'Western Cape')], max_length=6),
        ),
        migrations.AlterField(
            model_name='hcsstudybrandomization',
            name='province',
            field=models.CharField(choices=[('ZA-EC', 'Eastern Cape'), ('ZA-FS', 'Free State'), ('ZA-GP', 'Gauteng'), ('ZA-KZN', 'Kwazulu-Natal'), ('ZA-LP', 'Limpopo'), ('ZA-MP', 'Mpumalanga'), ('ZA-NC', 'Northern Cape'), ('ZA-NW', 'North-West'), ('ZA-WC', 'Western Cape')], max_length=6),
        ),
        migrations.AlterField(
            model_name='healthcheckuserprofile',
            name='province',
            field=models.CharField(choices=[('ZA-EC', 'Eastern Cape'), ('ZA-FS', 'Free State'), ('ZA-GP', 'Gauteng'), ('ZA-KZN', 'Kwazulu-Natal'), ('ZA-LP', 'Limpopo'), ('ZA-MP', 'Mpumalanga'), ('ZA-NC', 'Northern Cape'), ('ZA-NW', 'North-West'), ('ZA-WC', 'Western Cape')], max_length=6),
        ),
    ]
