# Generated by Django 2.2.20 on 2021-05-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="RedirectUrl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="https://hub.momconnect.za/confirmredirect",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("content", models.TextField(default="This entry has no copy")),
                (
                    "refresh_url",
                    models.CharField(
                        default="https://hub.momconnect.za", max_length=200
                    ),
                ),
                (
                    "symptom_check_url",
                    models.CharField(
                        default="http://symptomcheck.co.za", max_length=200
                    ),
                ),
                ("parameter", models.IntegerField(blank=True, null=True)),
                ("time_stamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RedirectUrlsEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_stamp", models.DateTimeField(auto_now=True)),
                (
                    "url",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ada.RedirectUrl",
                    ),
                ),
            ],
        ),
    ]
