# Generated by Django 2.2.20 on 2021-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirecturl',
            name='refresh_url',
            field=models.CharField(default='https://hub.momconnect.za', max_length=200),
        ),
    ]
