# Generated by Django 2.2.20 on 2021-05-03 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedirectUrls',
            new_name='RedirectUrl',
        ),
    ]
