# Generated by Django 2.2.20 on 2021-05-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ada", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="redirecturl",
            name="symptom_check_url",
            field=models.URLField(default="http://symptomcheck.co.za"),
        )
    ]
