# Generated by Django 2.2.20 on 2021-05-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0002_auto_20210503_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirecturl',
            name='content',
            field=models.TextField(default='This has no copy'),
        ),
    ]
