# Generated by Django 2.2.20 on 2021-05-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ada", "0003_remove_redirecturl_refresh_url")]

    operations = [
        migrations.AlterField(
            model_name="redirecturl",
            name="content",
            field=models.TextField(
                default="This entry has no copy",
                help_text="The content of the mesage that this link was sent in",
            ),
        )
    ]
