# Generated by Django 2.2.20 on 2021-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ada", "0004_auto_20210506_0726")]

    operations = [
        migrations.AlterField(
            model_name="redirecturl",
            name="parameter",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="redirecturl",
            name="url",
            field=models.URLField(
                blank=True,
                default="https://hub.momconnect.za/confirmredirect",
                max_length=255,
            ),
        ),
    ]
