# Generated by Django 2.2.20 on 2021-05-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0004_auto_20210503_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirecturlsentry',
            name='urls',
        ),
    ]
