# Generated by Django 2.2.20 on 2021-05-10 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ada", "0005_auto_20210507_1256")]

    operations = [
        migrations.AlterField(
            model_name="redirecturlsentry",
            name="url",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ada.RedirectUrl",
            ),
        )
    ]
