# Generated by Django 2.2.20 on 2021-05-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0006_redirecturlsentry_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirecturl',
            name='urls',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
