# Generated by Django 2.2.20 on 2021-05-10 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("ada", "0006_auto_20210510_0507")]

    operations = [migrations.RemoveField(model_name="redirecturl", name="url")]
