# Generated by Django 2.2.20 on 2021-05-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0008_redirecturl_refresh_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirecturl',
            name='refresh_url',
        ),
    ]
