# Generated by Django 2.2.20 on 2021-05-11 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("ada", "0009_redirecturlsentry_parameter")]

    operations = [migrations.RemoveField(model_name="redirecturl", name="url")]
