# Generated by Django 2.2.20 on 2021-05-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ada", "0010_remove_redirecturl_url")]

    operations = [
        migrations.AddField(
            model_name="redirecturl",
            name="url",
            field=models.URLField(
                blank=True,
                default="https://hub.momconnect.za/confirmredirect",
                max_length=255,
            ),
        )
    ]
