# Generated by Django 2.2.20 on 2021-05-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0010_redirecturl_refresh_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirecturl',
            name='symptom_check_url',
            field=models.CharField(default='http://symptomcheck.co.za', max_length=200),
        ),
        migrations.AlterField(
            model_name='redirecturl',
            name='content',
            field=models.TextField(default='This entry has no copy'),
        ),
    ]
