# Generated by Django 2.2.20 on 2021-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0011_auto_20210504_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirecturl',
            name='parameter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redirecturl',
            name='urls',
            field=models.URLField(blank=True, default='https://hub.momconnect.za/confirmredirect', max_length=255, null=True),
        ),
    ]
