# Generated by Django 2.2.20 on 2021-05-11 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("ada", "0012_auto_20210511_0657")]

    operations = [migrations.RemoveField(model_name="redirecturl", name="url")]
