# Generated by Django 2.2.20 on 2022-03-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ada", "0013_remove_redirecturl_url")]

    operations = [
        migrations.CreateModel(
            name="ADAAssessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_uuid", models.CharField(max_length=255)),
                ("step", models.IntegerField(null=True)),
                ("optionId", models.IntegerField(blank=True, null=True)),
                ("user_input", models.IntegerField(blank=True, null=True)),
            ],
        )
    ]
