# Generated by Django 2.2.20 on 2022-04-26 16:27

import functools

from django.db import migrations, models

import ada.validators


class Migration(migrations.Migration):

    dependencies = [("ada", "0013_remove_redirecturl_url")]

    operations = [
        migrations.CreateModel(
            name="AdaSelfAssessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_id", models.UUIDField()),
                (
                    "msisdn",
                    models.CharField(
                        max_length=255,
                        validators=[
                            functools.partial(
                                ada.validators._phone_number, *(), **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                ("assessment_id", models.UUIDField()),
                ("step", models.IntegerField(null=True)),
                ("optionId", models.IntegerField(blank=True, null=True)),
                ("user_input", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("choice", models.TextField(blank=True, null=True)),
                (
                    "pdf_media_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        )
    ]
