# Generated by Django 2.2.20 on 2022-03-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ada", "0014_adaassessment")]

    operations = [
        migrations.RenameField(
            model_name="adaassessment", old_name="user_uuid", new_name="contact_uuid"
        )
    ]
