# Generated by Django 2.2.20 on 2022-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ada", "0014_adaselfassessment")]

    operations = [
        migrations.AddField(
            model_name="adaselfassessment",
            name="roadblock",
            field=models.TextField(blank=True, null=True),
        )
    ]
