# Generated by Django 2.2.20 on 2022-03-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ada", "0015_auto_20220323_0646")]

    operations = [
        migrations.AddField(
            model_name="adaassessment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adaassessment",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
