# Generated by Django 2.2.20 on 2022-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ada", "0015_adaselfassessment_roadblock")]

    operations = [
        migrations.AlterField(
            model_name="adaselfassessment",
            name="roadblock",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
