# Generated by Django 2.2.20 on 2022-03-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ada", "0016_auto_20220323_0943")]

    operations = [
        migrations.RemoveField(model_name="adaassessment", name="description"),
        migrations.RemoveField(model_name="adaassessment", name="title"),
    ]
