# Generated by Django 2.2.20 on 2022-07-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ada", "0016_auto_20220524_1349")]

    operations = [
        migrations.CreateModel(
            name="CovidDataLakeEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
