# Generated by Django 2.2.20 on 2022-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ada", "0018_auto_20220323_1811")]

    operations = [
        migrations.AddField(
            model_name="adaassessment",
            name="title",
            field=models.TextField(blank=True, null=True),
        )
    ]
