# Generated by Django 2.1.2 on 2018-10-15 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0007_auto_20180212_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='change',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='registrations.Source'),
        ),
        migrations.AlterField(
            model_name='change',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
