# Generated by Django 2.2.2 on 2019-06-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("changes", "0008_auto_20181015_1002")]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="registrant_id",
            field=models.CharField(db_index=True, max_length=36),
        )
    ]
