# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20160722_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
