# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-01 10:21
from __future__ import unicode_literals

from django.db import migrations


def move_limited_to_partial(apps, schema_editor):
    Source = apps.get_model('registrations', 'Source')
    Source.objects.filter(authority='hw_limited')\
        .update(authority='hw_partial')


def move_partial_to_limited(apps, schema_editor):
    Source = apps.get_model('registrations', 'Source')
    Source.objects.filter(authority='hw_partial')\
        .update(authority='hw_limited')


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_rename_limited_authority_to_partial'),
    ]

    operations = [
        migrations.RunPython(move_limited_to_partial, move_partial_to_limited),
    ]
