# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("registrations", "0011_auto_20180227_1517")]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="The ID of the registration in the external service that created the registration",
                max_length=100,
                null=True,
                unique=True,
            ),
        )
    ]
