# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 14:18
from __future__ import unicode_literals

from django.db import migrations


def create_rthb_nurseconnect_position_tracker(apps, schema_editor):
    PositionTracker = apps.get_model('registrations', 'PositionTracker')
    PositionTracker.objects.get_or_create(label='nurseconnect_rthb')


def destroy_rthb_nurseconnect_position_tracker(apps, schema_editor):
    PositionTracker = apps.get_model('registrations', 'PositionTracker')
    PositionTracker.objects.filter(label='nurseconnect_rthb').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_historicalpositiontracker_positiontracker'),
    ]

    operations = [
        migrations.RunPython(
            create_rthb_nurseconnect_position_tracker,
            destroy_rthb_nurseconnect_position_tracker
        ),
    ]
