# Generated by Django 2.1.2 on 2019-05-28 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("registrations", "0017_create_whatsapp_contact")]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "permissions": [
                    (
                        "subscription_check_registration",
                        "Can perform a subscription check",
                    )
                ]
            },
        )
    ]
