# Generated by Django 2.2.1 on 2019-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("registrations", "0018_add_subscription_check_permission")]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="reg_type",
            field=models.CharField(
                choices=[
                    ("momconnect_prebirth", "MomConnect pregnancy registration"),
                    ("momconnect_postbirth", "MomConnect baby registration"),
                    ("whatsapp_prebirth", "WhatsApp MomConnect pregnancy registration"),
                    ("whatsapp_postbirth", "WhatsApp MomConnect baby registration"),
                    ("nurseconnect", "Nurseconnect registration"),
                    ("whatsapp_nurseconnect", "WhatsApp Nurseconnect registration"),
                    ("pmtct_prebirth", "PMTCT pregnancy registration"),
                    (
                        "whatsapp_pmtct_prebirth",
                        "WhatsApp PMTCT pregnancy registration",
                    ),
                    ("pmtct_postbirth", "PMTCT baby registration"),
                    ("whatsapp_pmtct_postbirth", "WhatsApp PMTCT baby registration"),
                    ("loss_general", "Loss general registration"),
                    (
                        "jembi_momconnect",
                        "Jembi MomConnect registration. Set temporarily until we calculate which registration it should be",
                    ),
                ],
                max_length=30,
            ),
        )
    ]
