# Generated by Django 2.2.4 on 2019-10-31 11:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("registrations", "0020_add_cclinic_code")]

    operations = [
        migrations.CreateModel(
            name="JembiSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("request_data", django.contrib.postgres.fields.jsonb.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("submitted", models.BooleanField(default=False)),
                ("response_status_code", models.IntegerField(default=None, null=True)),
                (
                    "response_headers",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("response_body", models.TextField(blank=True, default="")),
            ],
        )
    ]
