# Generated by Django 2.2.13 on 2020-09-21 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("registrations", "0023_migrate_wacontact_v1_data")]

    operations = [migrations.DeleteModel(name="WhatsAppContact")]
