# Generated by Django 2.2.13 on 2020-09-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("registrations", "0025_auto_20200921_1117")]

    operations = [
        migrations.AddIndex(
            model_name="cliniccode",
            index=models.Index(fields=["code"], name="registratio_code_8da953_idx"),
        )
    ]
