# Generated by Django 2.2.13 on 2020-09-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("registrations", "0026_auto_20200922_0946")]

    operations = [
        migrations.RemoveIndex(
            model_name="cliniccode", name="registratio_code_8da953_idx"
        ),
        migrations.AddIndex(
            model_name="cliniccode",
            index=models.Index(fields=["value"], name="registratio_value_a1dec5_idx"),
        ),
    ]
