# Generated by Django 2.2.13 on 2021-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("registrations", "0027_auto_20200922_1041")]

    operations = [
        migrations.AddField(
            model_name="cliniccode",
            name="location",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliniccode",
            name="province",
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
