# Generated by Django 4.1.7 on 2024-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0029_alter_historicalpositiontracker_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliniccode",
            name="area_type",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cliniccode",
            name="district",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cliniccode",
            name="municipality",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cliniccode",
            name="unit_type",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
