# Generated by Django 2.2.24 on 2022-03-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MqrStrata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(max_length=25)),
                ("weeks_pregnant_bucket", models.CharField(max_length=12)),
                ("age_bucket", models.CharField(max_length=12)),
                ("next_index", models.IntegerField(default=0)),
                ("order", models.CharField(max_length=50)),
            ],
        ),
    ]
