# Generated by Django 2.2.24 on 2022-03-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mqr", "0002_baselinesurveyresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselinesurveyresult",
            name="airtime_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="baselinesurveyresult",
            name="airtime_sent_at",
            field=models.DateTimeField(null=True),
        ),
    ]
