# Generated by Django 2.2.24 on 2022-03-22 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mqr", "0004_auto_20220322_0733"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baselinesurveyresult",
            old_name="vaccine_benifits",
            new_name="vaccine_benefits",
        ),
    ]
