# Generated by Django 2.2.24 on 2022-04-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mqr", "0007_auto_20220323_0852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselinesurveyresult",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("never_married", "Never married"),
                    ("married", "Married"),
                    ("separated_or_divorced", "Separated or divorced"),
                    ("widowed", "Widowed"),
                    ("partner_or_boyfriend", "Have a partner or boyfriend"),
                    ("skip", "Skip"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
